from typing import TextIO

from scipy.special import roots_legendre


class LegendreGenerator:
    def generate(self, output="src/gauss_legendre_tbl.h", n=100):
        with open(output, mode="w") as f:
            self.generate_into(f, n)

    def generate_into(self, writer: TextIO, n=100) -> None:
        writer.write(
            "// autogenerated do not edit\n"
            "\n"
            "#ifndef QUAD_GAUSS_LEGENDRE_TBL_H\n"
            "#define QUAD_GAUSS_LEGENDRE_TBL_H\n"
            "\n"
            f"#define QUAD_TBL_CHECK_LEGENDRE(n) ((n) >= 2 && (n) <= {n})\n"
            "#define QUAD_TBL_OFFSET_LEGENDRE(n) (((n) - 2) * ((n) + 1))\n"
            "\n"
            "// clang-format off\n"
            "\n"
            "static const double quad_roots_legendre[] = {\n"
        )

        for n in range(2, n + 1):
            writer.write(f"    // n = {n}\n")
            roots, weights = roots_legendre(n)
            for root, weight in zip(roots, weights):
                writer.write(f"    {weight:.17g}, {root:.17g},\n")

        writer.write(
            "};\n\n// clang-format on\n\n#endif /* QUAD_GAUSS_LEGENDRE_TBL_H */\n"
        )


def main():
    LegendreGenerator().generate()


if __name__ == "__main__":
    main()
